# Generated by Django 4.2.7 on 2026-04-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='student', max_length=50),
        ),
    ]
