# Generated by Django 4.2.7 on 2026-04-08 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructorapp', '0004_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('submission_file', models.FileField(upload_to='submissions/')),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='instructorapp.assignment')),
            ],
            options={
                'db_table': 'submissions',
            },
        ),
    ]
